language: node_js
node_js:
  - "node"
before_script:
  - npm install -g raml2html raml2html-markdown-theme
  - wget https://github.com/JiscRDSS/rdss-raml-validation-test/archive/master.zip
  - unzip master.zip
  - cd master && npm install
script: cd master && node index.js ../api.raml && bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "f5ec8fa293c6"

