language: node_js
node_js:
  - "node"
before_script:
  - npm install -g raml2html raml2html-markdown-theme
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "f5ec8fa293c6"
  - COMMIT_AUTHOR_EMAIL: "deploy@travis-ci.org"
