#%RAML 1.0
title: JISC Organisation API
version: v1
baseUri: https://www.jisc.ac.uk
types:
  Organisation:
    type: object
    properties:
      name: string
      type: string
      displayId: number
      billingId: number
/organisations:
  get:
    responses:
      200:
        body:
          application/json:
            type: Organisation[]
            example: |
              [
                {
                  "name": "University of Winchester",
                  "type": "Type1",
                  "displayId": 274,
                  "billingId": 20059
                },
                {
                  "name": "Imperial College of Science, Technology and Medicine",
                  "type": "Type2",
                  "displayId": 1539,
                  "billingId": 1539
                }
              ]
/organisations/{name}:
  get:
    responses:
      200:
        body:
          application/json:
            type: Organisation
            example: |
              {
                "name": "University of Winchester",
                "type": "Type1",
                "displayId": 274,
                "billingId": 20059
              }
/organisations/{type}:
  get:
    responses:
      200:
        body:
          application/json:
            type: Organisation[]
            example: |
              [
                {
                  "name": "University of Winchester",
                  "type": "Type1",
                  "displayId": 274,
                  "billingId": 20059
                },
                {
                  "name": "Imperial College of Science, Technology and Medicine",
                  "type": "Type2",
                  "displayId": 1539,
                  "billingId": 1539
                }
              ]
