#%RAML 1.0
title: JISC Organisation API
version: v1
baseUri: https://www.jisc.ac.uk
types:
  OrganisationType:
    type: string
    enum: ["charity",
           "commercial",
           "funder",
           "furtherEducation",
           "government",
           "health",
           "higherEducation",
           "other",
           "professionalBody",
           "research",
           "school",
           "skills"]
  Organisation:
    type: object
    properties:
      organisationUUID: string
      organisationName: string
      organisationType: OrganisationType



/organisation:
  get:
    responses:
      200:
        body:
          application/json:
            type: Organisation[]
            example: |
              [
                {
                  "organisationUUID": "274",
                  "organisationName": "University of Winchester",
                  "organisationType": "higherEducation"
                },
                {
                  "organisationUUID": "1539",
                  "organisationName": "Imperial College of Science, Technology and Medicine",
                  "organisationType": "charity"
                }
              ]
/organisation/{organisationUUID}:
  get:
    responses:
      200:
        body:
          application/json:
            type: Organisation
            example: |
              {
                "organisationUUID": "274",
                "organisationName": "University of Winchester",
                "organisationType": "higherEducation"
              }
      404:
        body:
          application/json:
            type: object
            example: |
              {
                "error": "Organisation was not found."
              }
/organisation/type/{organisationType}:
  uriParameters:
    organisationType:
      type: OrganisationType
  get:
    responses:
      200:
        body:
          application/json:
            type: Organisation[]
            example: |
              [
                {
                  "organisationUUID": "240",
                  "organisationName": "St Mary's University, Twickenham",
                  "organisationType": "charity"
                },
                {
                  "organisationUUID": "1539",
                  "organisationName": "Imperial College of Science, Technology and Medicine",
                  "organisationType": "charity"
                }
              ]
      400:
        description: |
          "Organisation type is invalid."
        body:
            application/json:
              type: object
              example: |
                {
                  "error": "Organisation type is invalid. Look up for valid types."
                }
